### ISSUE TITLE
Wrong Encoding

### ISSUE THREAD

**Issue by pakmans** [pvinton/QGIS-EncodedPolylineExporter-plugin#5]
Doesn't seem to work correctly.
In QGis:
![selection_009](https://user-images.githubusercontent.com/360079/29730844-a10f8870-89a7-11e7-8066-c146fa192806.png)

In Google's [Interactive Polyline Encoder Utility](https://developers.google.com/maps/documentation/utilities/polylineutility):

![selection_007](https://user-images.githubusercontent.com/360079/29730849-a4241c56-89a7-11e7-9230-a4f89b2876ee.png)

Original shapefile:
[ASUR-Trazo.zip](https://github.com/pvinton/QGIS-EncodedPolylineExporter-plugin/files/1252907/ASUR-Trazo.zip)

**Comment by pvinton** [comment]
Are you sure that the shapefile in the attached .zip is the exact same thing used to plot the detail in the second photo?  This is what I see when I plot `ASUR-Trazo.shp` **before** using the exporter.  
![image](https://user-images.githubusercontent.com/5711885/29783342-adf20708-8be5-11e7-8b2f-89483fad03e7.png)


Maybe the shapefile was simplified?  From what I can see, the exporter is doing exactly what it is supposed to.

**Comment by pakmans** [comment]
Geez, you are right. I tried again today, and it is working fine. I really don't know what happened, but I was getting those funky markers at the end... sorry for bothering.
